./gradlew generateVersionSVG generateReadme clean assemble\
 core:publishReleasePublicationToSonatypeRepository\
 rx1:publishReleasePublicationToSonatypeRepository\
 rx2:publishReleasePublicationToSonatypeRepository\
 rx3:publishReleasePublicationToSonatypeRepository\
 coroutines:publishReleasePublicationToSonatypeRepository